name: Run Scraper Daily

on:
  schedule:
    - cron: '* * * * *'  # Runs at 7:00 AM IST daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          GOOGLE_CREDENTIALS_BASE64_V2: ${{ secrets.GOOGLE_CREDENTIALS_BASE64_V2 }}
        run: node index.js
