name: NREGA Scraper Daily

on:
  schedule:
    - cron: "0 1 * * *"  # Every day at 1:00 AM UTC
  workflow_dispatch:     # Allow manual run

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run importtable.js
        run: node importtable.js
